### ISSUE TITLE
Facing issues in own implementation

### ISSUE THREAD

**Issue by Ben-schlch** [hansalemaos/getevent_sendevent#2]
Your project is really useful. I like your implementation. 
I tried to implement it in C++. But for myself it does sadly not work. 

When running the "dd" command manually, I get following response:

dd: /dev/input/event3: write error: Invalid argument
0+1 records in
0+0 records out
0 bytes (0 B) copied, 0.000109 s, 0 B/s

If I write to other files, it works. ADB is running in root. Running it like 
"adb shell su 0 dd bs...." does also not help. 

Do you have any idea why this is happening and how to fix?

Is the problem the content of this file?
cat /data/local/tmp/sendeventBuffer.tmp
3 57 0
3 53 17185
3 54 23346
3 58 1024

**Comment by hansalemaos** [comment]
I am glad that you like it :) 

Did you encode the data? You have to send it in that format:
```
    FORMAT = "llHHI"
    EVENT_SIZE = struct.calcsize(FORMAT)
    df["aa_struct"] = df.apply(
        lambda x: struct.pack(
            FORMAT, 1, 2, int(x.aa_type_int), int(x.aa_code_int), int(x.aa_value_int),
        ),
        axis=1,
    )
    df["aa_struct_real"] = df.apply(
        lambda x: struct.pack(
            FORMAT, 3, 2, int(x.aa_type_int), int(x.aa_code_int), int(x.aa_real_coords),
        ),
        axis=1,
    )
```

**Comment by Ben-schlch** [comment]
Thank you for the quick response. You are totally right. Obviously it needs to be in binary. 
But this encoding I did not ensure and also I do not fully understand it.
So numbers 3 to 5 are event type, code, value. But number 1 and 2 are random placeholders? Maybe I miss something.

**Comment by hansalemaos** [comment]
One of those moments that I recognize the importance of writing comments. hahaha
Watch this video: https://www.youtube.com/watch?v=BNDtruH6frI
At the beginning, you see the events and the event codes. Here is a better explanation of those codes: https://source.android.com/docs/core/interaction/input/getevent Check out the dicts at the beginning of the source code, they will also help you.
